/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rttywx_decode.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b2cad88169a6dc33da8c68a1cdc0c179)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rttywx/rttywx_decode.h>
// pydoc.h is automatically generated in the build directory
#include <rttywx_decode_pydoc.h>

void bind_rttywx_decode(py::module& m)
{

    using rttywx_decode    = ::gr::rttywx::rttywx_decode;


    py::class_<rttywx_decode, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<rttywx_decode>>(m, "rttywx_decode", D(rttywx_decode))

        .def(py::init(&rttywx_decode::make),
           py::arg("sampling_rate"),
           py::arg("filename") = nullptr,
           py::arg("reverse") = false,
           D(rttywx_decode,make)
        )
        



        ;




}








