/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-rttywx
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RTTYWX_API_H
#define INCLUDED_RTTYWX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_rttywx_EXPORTS
#define RTTYWX_API __GR_ATTR_EXPORT
#else
#define RTTYWX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RTTYWX_API_H */
